
<!-- SAVE THIS AS index.html -->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Rizwan Khan | Fitness & Design</title>
  <style>
    /* Yahan purana style hai— zarurat pade to update kar sakte hain */
    body { margin:0; font-family:Arial; background:#fff; color:#333; }
    header { background:#111; color:#fff; padding:20px; text-align:center; }
    nav { background:#222; display:flex; justify-content:center; gap:20px; padding:10px; }
    nav a { color:#fff; text-decoration:none; font-weight:bold; }
    section { padding:40px 20px; max-width:1000px; margin:auto; }
    .buttons a { background:#007BFF; color:#fff; padding:10px 20px; margin:10px; border-radius:5px; text-decoration:none; }
    .services, .ebook, .contact { background:#f9f9f9; border-radius:8px; padding:20px; margin-top:20px; }
    footer { background:#111; color:#fff; text-align:center; padding:15px; }
  </style>
</head>
<body>
  <header><h1>Rizwan Khan</h1><p>Fitness Coach & Graphic Designer</p></header>
  <nav>
    <a href="#home">Home</a>
    <a href="#ebook">Ebook</a>
    <a href="#services">Design Services</a>
    <a href="#contact">Contact</a>
  </nav>
  <section id="home" class="hero">
    <h2>Build Your Body & Your Brand — All from Home</h2>
    <div class="buttons"><a href="#ebook">Buy My Ebook</a><a href="#services">Hire Me</a></div>
  </section>
  <section id="ebook" class="ebook">
    <h3>📘 Fit at Home - Your Fitness Guide</h3>
    <p><strong>Author:</strong> Rizwan Khan</p>
    <p>This beginner-friendly ebook helps you get in shape without going to the gym...</p>
    <a href="#" class="buttons">Buy Now</a>
  </section>
  <section id="services" class="services">
    <h3>🎨 Graphic Design Services</h3>
    <ul><li>Product Packaging</li><li>Ebook Covers</li><li>Social Media Graphics</li><li>Thumbnails & Branding</li></ul>
    <a href="https://wa.me/923192995990" class="buttons" target="_blank">Contact on WhatsApp</a>
  </section>
  <section id="contact" class="contact">
    <h3>📞 Contact Me</h3>
    <p><strong>Email:</strong> kingkingobaloch@gmail.com</p>
    <p><strong>WhatsApp:</strong> 03192995990</p>
  </section>
  <footer>&copy; 2025 Rizwan Khan | All rights reserved.</footer>
</body>
</html>
